BEGIN;

ALTER TABLE artist_stats
    ADD COLUMN IF NOT EXISTS sum_p1 INTEGER DEFAULT 0 CHECK (sum_p1 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p2 INTEGER DEFAULT 0 CHECK (sum_p2 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p3 INTEGER DEFAULT 0 CHECK (sum_p3 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p4 INTEGER DEFAULT 0 CHECK (sum_p4 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p5 INTEGER DEFAULT 0 CHECK (sum_p5 >= 0);

ALTER TABLE venue_stats
    ADD COLUMN IF NOT EXISTS sum_p1 INTEGER DEFAULT 0 CHECK (sum_p1 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p2 INTEGER DEFAULT 0 CHECK (sum_p2 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p3 INTEGER DEFAULT 0 CHECK (sum_p3 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p4 INTEGER DEFAULT 0 CHECK (sum_p4 >= 0),
    ADD COLUMN IF NOT EXISTS sum_p5 INTEGER DEFAULT 0 CHECK (sum_p5 >= 0);

COMMIT;
