BEGIN;

ALTER TABLE artist_stats
    DROP COLUMN IF EXISTS sum_p1,
    DROP COLUMN IF EXISTS sum_p2,
    DROP COLUMN IF EXISTS sum_p3,
    DROP COLUMN IF EXISTS sum_p4,
    DROP COLUMN IF EXISTS sum_p5;

ALTER TABLE venue_stats
    DROP COLUMN IF EXISTS sum_p1,
    DROP COLUMN IF EXISTS sum_p2,
    DROP COLUMN IF EXISTS sum_p3,
    DROP COLUMN IF EXISTS sum_p4,
    DROP COLUMN IF EXISTS sum_p5;

COMMIT;
